### ISSUE TITLE
Warning when saving vocabulary

### ISSUE THREAD

**Issue by padeoe** [thunlp/OpenCLaP#1]
The warning shows when saving the models:
```Python
>>> tokenizer.save_vocabulary(model_dir)
Saving vocabulary to vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
```

**Comment by haoxizhong** [comment]
There are some special spaces in the vocabulary. The package "pytorch-pretrained-bert" will regard these spaces as empty characters, so we suggest you write your own tokenizer or just ignore it. We will remove these spaces in vocab.txt later.
