### ISSUE TITLE
求教两个训练细节问题

### ISSUE THREAD

**Issue by IT-Xue** [thunlp/OpenCLaP#16]
1、next sentence prediction 是以什么标点符号进行分割作为上下句的（逗号、句号、分号？）。
2、next sentence prediction 单句大概长度都是多少？
非常感谢。

**Comment by zzy14** [comment]
英文是用句号分割的，对应中文模型应该也可以用句号。长度应该是没有限制，只要不大于max_len即可。另外，roberta验证了next sentence prediction作用不大，后续模型也很少采用这个策略了。
